include:
  # TODO Include V2X Hub docker compose as an OCI (Open Container Initiative) artifact
  - path: ../V2X-Hub/configuration/docker-compose.yml
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
       - "2181:2182"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - zookeeper-datavolume:/opt/zookeeper-3.4.13/data
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on: 
      - zookeeper
    ports:
      - "9092:9092"
    # Health check to confirm kafka server is healthy (script is a client) and all topics 
    # have been created (time_sync is last topic).
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--describe", "--bootstrap-server", "127.0.0.1:9092", "--topic", "time_sync"]
      interval: 2s
      timeout: 10s
      retries: 10
    environment:
      DOCKER_HOST_IP:  ${INFRASTRUCTURE_IP:-127.0.0.1}
      KAFKA_ADVERTISED_HOST_NAME:  ${INFRASTRUCTURE_IP:-127.0.0.1}
      KAFKA_CREATE_TOPICS: "\
        v2xhub_scheduling_plan_sub:1:1,\
        v2xhub_bsm_in:1:1,\
        v2xhub_mobility_operation_in:1:1,\
        v2xhub_mobility_path_in:1:1,\
        vehicle_status_intent_output:1:1,\
        v2xhub_map_msg_in:1:1,\
        modified_spat:1:1,\
        desired_phase_plan:1:1,\
        tsc_config_state:1:1,\
        v2xhub_sim_sensor_detected_object:1:1,\
        v2xhub_sdsm_sub:1:1,\
        desire_phase_plan:1:1,\
        v2xhub_sdsm_tra:1:1,\
        time_sync:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - kafka-datavolume:/kafka/kafka-logs
##############################################################
# Kafka Owl for monitoring kafka traffic. UI can be accessed on 
# configurable port set in performance/kowl.yaml NOTE: IS NOT 
# NECESSARY FOR DEPLOYMENT BUT HELFUL FOR DEBUGGING! 
################################################################
  kowl:
    image: quay.io/cloudhut/kowl
    container_name: kowl
    restart: on-failure
    network_mode: host
    profiles: ["debug"]
    depends_on:
      kafka:
        condition: service_healthy  
    environment:
      CONFIG_FILEPATH: /etc/kowl/kowl.yaml
    volumes:
      - ./performance/kowl.yaml:/etc/kowl/kowl.yaml
  scheduling_service:
    image: ${STOL_ORG:-usdotfhwastoldev}/scheduling_service:${STOL_TAG:-develop}
    command: sh -c "/wait && /home/carma-streets/scheduling_service/build/scheduling_service"
    build: 
      context: .
      dockerfile: scheduling_service/Dockerfile
    container_name: scheduling_service
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    network_mode: host
    profiles: ["vehicle_scheduling", "signal_optimization"]
    depends_on:
      kafka:
        condition: service_healthy  
      intersection_model: 
        condition: service_started
      message_services: 
        condition: service_started
    volumes: 
      - ./scheduling_service/manifest.json:/home/carma-streets/scheduling_service/manifest.json
      - ./scheduling_service/logs/:/home/carma-streets/scheduling_service/logs/
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro     

  message_services:
    image: ${STOL_ORG:-usdotfhwastoldev}/message_services:${STOL_TAG:-develop}
    build: 
      context: .
      dockerfile: message_services/Dockerfile
    container_name: message_services
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    network_mode: host
    profiles : ["vehicle_scheduling", "signal_optimization"]
    depends_on:
      kafka:
        condition: service_healthy  
    environment:
      DOCKER_HOST_IP:  ${INFRASTRUCTURE_IP:-127.0.0.1}
    volumes: 
      - ./message_services/manifest.json:/home/carma-streets/message_services/manifest.json
      - ./MAP/:/home/carma-streets/message_services/MAP/
      - ./message_services/logs/:/home/carma-streets/message_services/logs/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  intersection_model:
    image: ${STOL_ORG:-usdotfhwastoldev}/intersection_model:${STOL_TAG:-develop}
    build: 
      context: .
      dockerfile: intersection_model/Dockerfile
    container_name: intersection_model
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    network_mode: host
    profiles: ["vehicle_scheduling", "signal_optimization"]
    depends_on:
      kafka:
        condition: service_healthy  
    environment:
      DOCKER_HOST_IP:  ${INFRASTRUCTURE_IP:-127.0.0.1}

    volumes: 
      - ./intersection_model/manifest.json:/home/carma-streets/intersection_model/manifest.json
      - ./MAP/:/home/carma-streets/intersection_model/MAP/
      - ./intersection_model/logs/:/home/carma-streets/intersection_model/logs/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  signal_opt_service:
    image: ${STOL_ORG:-usdotfhwastoldev}/signal_opt_service:${STOL_TAG:-develop}
    command: sh -c "/wait && /home/carma-streets/signal_opt_service/build/signal_opt_service"
    build: 
      context: .
      dockerfile: signal_opt_service/Dockerfile
    container_name: signal_opt_service
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    network_mode: host
    profiles: ["signal_optimization"]
    depends_on:
      kafka:
        condition: service_healthy  
      intersection_model:
        condition: service_started
      message_services:
        condition: service_started
      scheduling_service:
        condition: service_started
      tsc_service:
        condition: service_started   
    volumes: 
      - ./signal_opt_service/manifest.json:/home/carma-streets/signal_opt_service/manifest.json
      - ./signal_opt_service/logs/:/home/carma-streets/signal_opt_service/logs/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  tsc_service:
    image: ${STOL_ORG:-usdotfhwastoldev}/tsc_service:${STOL_TAG:-develop}
    command: sh -c "/wait && /home/carma-streets/tsc_client_service/build/traffic_signal_controller_service"
    build: 
      context: .
      dockerfile: tsc_client_service/Dockerfile
    container_name: tsc_service
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    network_mode: host
    profiles: ["signal_optimization", "vehicle_scheduling"]
    depends_on:
      kafka:
        condition: service_healthy  
      intersection_model:
        condition: service_started
    environment:
      DOCKER_HOST_IP:  ${INFRASTRUCTURE_IP:-127.0.0.1}
      SIMULATION_MODE: ${SIMULATION_MODE:-FALSE}
      CONFIG_FILE_PATH: ../manifest.json
      TIME_SYNC_TOPIC: time_sync
      LOGS_DIRECTORY: /home/carma-streets/tsc_client_service/logs/
    volumes: 
      - ./tsc_client_service/manifest.json:/home/carma-streets/tsc_client_service/manifest.json
      - ./tsc_client_service/logs/:/home/carma-streets/tsc_client_service/logs/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  sensor_data_sharing_service:
    image: ${STOL_ORG:-usdotfhwastoldev}/sensor_data_sharing_service:${STOL_TAG:-develop}
    build: 
      context: .
      dockerfile: sensor_data_sharing_service/Dockerfile
    container_name: sensor_data_sharing_service
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g
    network_mode: host
    profiles : ["cooperative_perception"]
    depends_on:
      kafka:
        condition: service_healthy  
    environment:
      SIMULATION_MODE: ${SIMULATION_MODE:-FALSE}
      CONFIG_FILE_PATH: /home/carma-streets/sensor_data_sharing_service/manifest.json
      TIME_SYNC_TOPIC: time_sync
      LOGS_DIRECTORY: home/carma-streets/sensor_data_sharing_service/logs/
      LANELET2_MAP: ${LANELET2_MAP:-/home/carma-streets/intersection_model/MAP/lanelet2_map.osm}
      INFRASTRUCTURE_ID: ${INFRASTRUCTURE_ID:-rsu_1234}
      INFRASTRUCTURE_NAME: ${INFRASTRUCTURE_NAME:-East Intersection}
      INFRASTRUCTURE_IP: ${INFRASTRUCTURE_IP:-127.0.0}
      SENSOR_JSON_FILE_PATH: ${SENSOR_JSON_FILE_PATH:-/home/carma-streets/sensor_configurations/sensors.json}

    volumes: 
      - ./sensor_data_sharing_service/manifest.json:/home/carma-streets/sensor_data_sharing_service/manifest.json
      - ./sensor_data_sharing_service/logs/:/home/carma-streets/sensor_data_sharing_service/logs/
      - ./MAP/:/home/carma-streets/intersection_model/MAP/
      - ./sensor_configurations/:/home/carma-streets/sensor_configurations/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
volumes:
    kafka-datavolume:
    zookeeper-datavolume:
