version: '3.7'
services:
  # Uncomment for streets service base dev environment
  streets_service_base:
    build:
      context: .
      dockerfile: ./streets_service_base/Dockerfile
      args:
        UBUNTU_CODENAME: bionic
  # Uncomment for streets service base lanelet aware dev environment
  # streets_service_base_lanelet_aware:
  #   build:
  #     context: .
  #     dockerfile: ./streets_service_base_lanelet_aware/Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
 
