name: Build and Push Base Images
on:
    pull_request:
      types: [opened, synchronize, reopened]
    push:
      branches: [develop, master]
jobs:   
    docker-build:
        strategy:
            matrix:
                include:
                 - ubuntu-codename: bionic
                 - ubuntu-codename: focal
                 - ubuntu-codename: jammy
        runs-on: ubuntu-latest
        steps:
          - name: Log in to the Container registry
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Docker Build Streets Service Base
            uses: docker/build-push-action@v3
            with:
                push: true
                build-args: |
                    UBUNTU_CODENAME=${{ matrix.ubuntu-codename }}
                tags: usdotfhwastoldev/streets_service_base:${{ matrix.ubuntu-codename }}
                file: ./streets_service_base/Dockerfile
          - name: Docker Build Streets Service Base Lanelet Aware
            uses: docker/build-push-action@v3
            with:
              push: true
              tags: usdotfhwastoldev/streets_service_base_lanelet_aware:bionic
              file: ./streets_service_base_lanelet_aware/Dockerfile          
 