name: Docker Hub build
on:
  push:
    branches:
      - develop
      - master
      - "release/*"
    tags:
      - "carma-system-*"

jobs:
  intersection_model:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest-16-cores
      file: intersection_model/Dockerfile
      image_name: intersection_model
  message_services:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest-16-cores
      file: message_services/Dockerfile
      image_name: message_services
  tsc_client_service:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest-16-cores
      file: tsc_client_service/Dockerfile
      image_name: tsc_service
  scheduling_service:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest-16-cores
      file: scheduling_service/Dockerfile
      image_name: scheduling_service
  signal_opt_service:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest-16-cores
      file: signal_opt_service/Dockerfile
      image_name: signal_opt_service
  sensor_data_sharing_service:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      runner: ubuntu-latest-16-cores
      file: sensor_data_sharing_service/Dockerfile
      image_name: sensor_data_sharing_service
    
