name: Docker build
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  streets_service_base:
    strategy:
      matrix:
        UBUNTU_CODENAME: [ focal, jammy ]
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main

    with:
      file: streets_service_base/Dockerfile
      additional_build_args: |
        UBUNTU_CODENAME=${{ matrix.UBUNTU_CODENAME }}
  streets_service_base_lanelet_aware:
    needs: streets_service_base
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
      file: streets_service_base_lanelet_aware/Dockerfile
      additional_build_args: |
        UBUNTU_CODENAME=focal
  message_services:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
        file: message_services/Dockerfile
  intersection_model:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
        file: intersection_model/Dockerfile
  scheduling_service:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
        file: scheduling_service/Dockerfile
  signal_opt_service:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
        file: signal_opt_service/Dockerfile
  sensor_data_sharing_service:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
        file: sensor_data_sharing_service/Dockerfile
  tsc_client_service:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
        file: tsc_client_service/Dockerfile